#!/bin/sh

set -e

# Configuration
USER_NAME="helfertool"

DOCKER_NAME="helfertool"
DOCKER_IMAGE="helfertool/helfertool"

CONFIG_DIR="/etc/helfertool"
DATA_DIR="/srv/helfertool"

# Command: start
if [ "$1" = "start" ] ; then
    if ! [ -z "$(docker ps -a | grep "$DOCKER_NAME")" ] ; then
        /usr/bin/docker stop "$DOCKER_NAME" || true
        /usr/bin/docker rm "$DOCKER_NAME" || true
    fi

    /usr/bin/docker run --rm --name "$DOCKER_NAME" \
        -p 127.0.0.1:8000:8000 \
        -e USERID=$(id -u "$USER_NAME") \
        -e GROUPID=$(id -g "$USER_NAME") \
        -v "$DATA_DIR:/data" \
        -v "$CONFIG_DIR:/config" \
        "$DOCKER_IMAGE"
# Command: stop
elif [ "$1" = "stop" ] ; then
    /usr/bin/docker stop "$DOCKER_NAME"
# Command: reload
elif [ "$1" = "reload" ] ; then
    /usr/bin/docker exec -t "$DOCKER_NAME" helfertool reload
# Command: download
elif [ "$1" = "download" ] ; then
    /usr/bin/docker pull "$DOCKER_IMAGE"
# Command: init
elif [ "$1" = "init" ] ; then
    /usr/bin/docker exec -it "$DOCKER_NAME" helfertool init
# Command: createadmin
elif [ "$1" = "createadmin" ] ; then
    /usr/bin/docker exec -it "$DOCKER_NAME" helfertool createadmin
# Command: manage
elif [ "$1" = "manage" ] ; then
    shift
    /usr/bin/docker exec -it "$DOCKER_NAME" helfertool manage $@
# Command: shell
elif [ "$1" = "shell" ] ; then
    shift
    /usr/bin/docker exec -it "$DOCKER_NAME" bash
# Help
else
    echo "helfertoolctl"
    echo ""
    echo "[Service]"
    echo "start\t\tStart docker container"
    echo "stop\t\tStop docker container"
    echo "reload\t\tReload application"
    echo "download\tDownload the latest Docker image"
    echo ""
    echo "[Helfertool]"
    echo "init\t\tInitialize Helfertool (only run once at the beginning!)"
    echo "createadmin\tCreate new adminitrator account"
    echo ""
    echo "[Advanced]"
    echo "manage\t\tRun Django manage.py command directly"
    echo "shell\t\tSpawn shell in docker container"

    exit 1
fi
